language: cpp

os:
  - osx
  - linux

before_install:
  - if [ "$TRAVIS_OS_NAME" == "linux" ] && [ "$CXX" == "g++" ]; then sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test; fi
  - if [ "$TRAVIS_OS_NAME" == "linux" ] && [ "$CXX" == "clang++" ]; then sudo add-apt-repository -y ppa:h-rayflood/llvm; fi
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then sudo apt-get update -qq; fi

install:
  # LINUX
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then sudo apt-get install -qq gnulib dh-make; fi
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then sudo apt-get install libwxgtk2.8-dev libxml2-dev autotools-dev automake; fi
  - if [ "$TRAVIS_OS_NAME" == "linux" ] && [ "$CXX" = "g++" ]; then sudo apt-get install -qq g++-4.7; fi
  - if [ "$TRAVIS_OS_NAME" == "linux" ] && [ "$CXX" = "g++" ]; then export CXX="g++-4.7" && export CC="gcc-4.7"; fi
  # OSX
  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then brew install gsed automake autoconf libtool wxmac; fi

before_script:
  - autoreconf -i -I/usr/share/gnulib/m4 -I `pwd`/m4

script:
  - ./configure && make

branches:
  only:
    - master

notifications:
  email:
    on_success: change
    on_failure: always